name: Build BlocksMod

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Compile BlocksMod
        run: |
          xcrun -sdk iphoneos clang++ -dynamiclib -arch arm64 \
          -fobjc-arc -O3 \
          BlocksMod.mm -o BlocksMod.dylib \
          -framework UIKit -framework Foundation -framework QuartzCore
          
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: BlocksMod-Payload
          path: BlocksMod.dylib
